# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - secret.yml

labels:
  - pairs:
      app: mongodb
    includeSelectors: true